(ns build
  (:require [clojure.tools.build.api :as b]
            [clojure.java.io :as io]
            [clojure.string :as str])
  (:import [java.nio.file Files]
           [java.nio.file.attribute PosixFilePermissions]
           [java.time LocalDate]
           [java.time.format DateTimeFormatter]))

(def lib 'pairwise/pairwise)
(def version "0.1.0")
(def class-dir "target/classes")
(def basis (b/create-basis {:project "deps.edn"}))
(def uber-file (format "target/%s-%s-standalone.jar" (name lib) version))
(def jar-file (format "target/%s-%s.jar" (name lib) version))

(defn clean [_]
  (b/delete {:path "target"}))

;; ---------------------------------------------------------------------------
;; LaTeX package
;; ---------------------------------------------------------------------------

(def sty-name "alignment-macros")
(def macros-source "resources/tikz/alignment-macros.tex")

(defn- sty-contents
  "Wrap the shared TikZ macros as a LaTeX2e package. The body is used verbatim
   so the package and the standalone output generated by pairwise.tikz-view can
   never disagree about the visual grammar."
  [body]
  (let [date (.format (LocalDate/now) (DateTimeFormatter/ofPattern "yyyy/MM/dd"))]
    (str "%% " sty-name ".sty --- DP alignment arrow macros\n"
         "%%\n"
         "%% GENERATED FILE --- DO NOT EDIT.\n"
         "%% Produced from " macros-source " by `clojure -T:build sty`.\n"
         "%% Edit that file and regenerate; edits made here will be lost.\n"
         "%%\n"
         "\\NeedsTeXFormat{LaTeX2e}\n"
         "\\ProvidesPackage{" sty-name "}[" date " DP alignment arrow macros]\n"
         "\n"
         "\\RequirePackage{tikz}\n"
         "\\RequirePackage{xcolor}\n"
         "\n"
         (str/trim body)
         "\n"
         "\n\\endinput\n")))

(defn sty
  "Generate alignment-macros.sty from the shared TikZ macro definitions.

   Writes to target/ by default. Pass :dest to write straight into a texmf
   tree, e.g.
     clojure -T:build sty :dest '\"/home/you/texmf/tex/latex/gtk\"'"
  [{:keys [dest]}]
  (let [source (io/file macros-source)
        _ (when-not (.exists source)
            (throw (ex-info (str "Missing " macros-source) {:file macros-source})))
        dir (io/file (or dest "target"))
        out (io/file dir (str sty-name ".sty"))]
    (.mkdirs dir)
    (spit out (sty-contents (slurp source)))
    (println "Wrote" (.getAbsolutePath out))
    (when-not dest
      (println "Copy it into your texmf tree, then run: mktexlsr"))))

(defn jar [_]
  (clean nil)
  (b/write-pom {:class-dir class-dir
                :lib lib
                :version version
                :basis basis
                :src-dirs ["src"]})
  (b/copy-dir {:src-dirs ["src" "resources"]
               :target-dir class-dir})
  (b/jar {:class-dir class-dir
          :jar-file jar-file}))

(defn uber [_]
  (clean nil)
  (b/copy-dir {:src-dirs ["src" "resources"]
               :target-dir class-dir})
  (b/compile-clj {:basis basis
                  :ns-compile '[pairwise.main]
                  :class-dir class-dir})
  (b/uber {:class-dir class-dir
           :uber-file uber-file
           :basis basis
           :main 'pairwise.main}))

(defn install
  "Install pairwise CLI to ~/bin"
  [_]
  (uber nil)
  (let [home     (System/getProperty "user.home")
        bin-dir  (io/file home "bin")
        jar-dest (io/file bin-dir "pairwise.jar")
        wrapper  (io/file bin-dir "pairwise")]
    (.mkdirs bin-dir)
    (io/copy (io/file uber-file) jar-dest)
    (spit wrapper (str "#!/usr/bin/env bash\n"
                       "exec java -jar \"" (.getAbsolutePath jar-dest) "\" \"$@\"\n"))
    (Files/setPosixFilePermissions (.toPath wrapper)
                                   (PosixFilePermissions/fromString "rwxr-xr-x"))
    (println "Installed to" (.getAbsolutePath bin-dir))
    (println "  " (.getAbsolutePath jar-dest))
    (println "  " (.getAbsolutePath wrapper))
    (let [path (System/getenv "PATH")]
      (when-not (some #(= (.getAbsolutePath bin-dir) %)
                      (clojure.string/split path (re-pattern (System/getProperty "path.separator"))))
        (println)
        (println "NOTE:" (.getAbsolutePath bin-dir) "is not on your PATH.")
        (println "Add this to your shell profile:")
        (println (str "  export PATH=\"" (.getAbsolutePath bin-dir) ":$PATH\""))))))
